Re-built dockerfile

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -37,7 +37,6 @@ script:
     fi
 # Testing httpd
  - HTTP_CODE=$( sleep 1 && curl -sLI 127.0.0.1:38080/index.html -o /dev/null -w '%{http_code}\n' )
- - PHP_TEST="Success"
 
 # Checking exit code
  - if [ ! "$HTTP_CODE" = "200" ]; then
@@ -55,14 +54,9 @@ script:
         HTTP_CONTENT=$(curl -s 127.0.0.1:38080/index.php);
         PHP_TEST=$( echo "$HTTP_CONTENT" | grep -q "http://www.php.net/" && echo "Success");
     fi
-# Print failure
- - if [ ! "$PHP_TEST" = "Success" ]; then
-        echo "### Test failed\n";
-        exit 1;
-    fi
-# Print success
- - if [ "$PHP_TEST" = "Success" ]; then
-        echo "### Test succeeded\n";
+# Check PHP test
+ - if [ "True" = "True" ]; then
+        if [ "$PHP_TEST" = "Success" ]; then echo "### Test succeeded\n"; else echo "### Test failed\n"; exit 1; fi;
     fi
 
 
