Re-built dockerfile

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -15,37 +15,37 @@ script:
 
 # Testing httpd container
  - if [ ! "$TEST_HTTPD_CONTAINER_STATUS" == "true" ]; then
-        echo -ne "Httpd container failed, print logs and exiting"
-        docker logs $TEST_HTTPD_CONTAINER_ID
-        exit 1
+        echo -ne "Httpd container failed, print logs and exiting";
+        docker logs $TEST_HTTPD_CONTAINER_ID;
+        exit 1;
     fi
 # Running PHP-FPM container
  - if [ True = True ]; then
-        TEST_PHP_CONTAINER_ID=$( docker run -d --net=container:dockerized-apache-alpine -v $CURDIR/volumes/test_webroot:/var/www/html quay.io/alphasocket/docker-magento-php-fpm-alpine:7.0 )
-        TEST_PHP_CONTAINER_STATUS=$(sleep 1 && docker inspect -f '{{.State.Running}}' $TEST_PHP_CONTAINER_ID)
+        TEST_PHP_CONTAINER_ID=$( docker run -d --net=container:dockerized-apache-alpine -v $CURDIR/volumes/test_webroot:/var/www/html quay.io/alphasocket/docker-magento-php-fpm-alpine:7.0 );
+        TEST_PHP_CONTAINER_STATUS=$(sleep 1 && docker inspect -f '{{.State.Running}}' $TEST_PHP_CONTAINER_ID);
     fi
 # Testing PHP-FPM container
  - if [ ! "$TEST_PHP_CONTAINER_STATUS" = "true" ]; then
-        echo -ne "PHP-FPM container failed, print logs and exiting"
-        docker logs $TEST_PHP_CONTAINER_ID
-        exit 1
+        echo -ne "PHP-FPM container failed, print logs and exiting";
+        docker logs $TEST_PHP_CONTAINER_ID;
+        exit 1;
     fi
 # Testing httpd
  - HTTP_CODE=$(curl -sLI 127.0.0.1:30000/index.html -o /dev/null -w '%{http_code}\n' )
 
 # Testing PHP service
  - if [ True = True ]; then
-        HTTP_CODE=$(curl -sLI 127.0.0.1:30000/index.php -o /dev/null -w '%{http_code}\n' )
+        HTTP_CODE=$(curl -sLI 127.0.0.1:30000/index.php -o /dev/null -w '%{http_code}\n' );
     fi
 # Checking exit code
  - if [ ! "$HTTP_CODE" == "200" ]; then
-        echo -ne "### Test failed, received HTTP code ${HTTP_CODE} printing log"
-        docker logs $TEST_APACHE_CONTAINER_ID
-        exit 1
+        echo -ne "### Test failed, received HTTP code ${HTTP_CODE} printing log";
+        docker logs $TEST_APACHE_CONTAINER_ID;
+        exit 1;
     fi
 # Print success
  - if [ "$HTTP_CODE" == "200" ]; then
-        echo -ne "### Test succeeded\n"
+        echo -ne "### Test succeeded\n";
     fi
 
 
